protection:
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: true
    required_review_thread_resolution: true
  
  required_status_checks:
    strict: true
    checks:
      - context: "Review Requirements"
        app_id: "github-actions"
  
  enforce_admins: true
  required_linear_history: true
  allow_force_pushes: false
  allow_deletions: false
  required_conversation_resolution: true
  
  restrictions:
    users: []
    teams: []
    apps: []

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        strict: true
      enforce_admins: true
      restrictions: null 