repository:
  name: 1pipe
  description: Development architecture patterns and CICD workflow templates
  homepage: https://github.com/ihsanmokhlisse/1pipe
  private: true
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: false  # We handle this with our custom workflow
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: true
        required_review_thread_resolution: true
      
      required_status_checks:
        strict: true
        checks:
          - context: "Review Requirements"
            app_id: "github-actions"
      
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true 