blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/ihsanmokhlisse/1pipe/wiki
    about: Check our documentation before creating an issue
  - name: 💬 Discussions
    url: https://github.com/ihsanmokhlisse/1pipe/discussions
    about: Please ask and answer questions here
  - name: 🔒 Security Policy
    url: https://github.com/ihsanmokhlisse/1pipe/security/policy
    about: Please report security vulnerabilities here 