name: 🚀 Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        
        Please fill out this form as completely as possible to help us understand your request.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Details
      description: If you have specific ideas about how to implement this feature, please share them here.
      placeholder: |
        Consider including:
        - Technical approach
        - Required dependencies
        - Potential impacts on existing features
        - Timeline estimates

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What area of the project does this feature affect?
      options:
        - Core Functionality
        - User Interface
        - Documentation
        - Performance
        - Security
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Blocking Progress)
        - High (Important for Next Release)
        - Medium (Nice to Have)
        - Low (Future Enhancement)
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What are the specific requirements for this feature to be considered complete?
      placeholder: |
        Example:
        - [ ] Feature can handle X cases
        - [ ] UI is responsive on mobile devices
        - [ ] Documentation is updated
        - [ ] Tests are added
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true 